export const PROFILE_TYPES = [
  {
    id: "individual-entrepreneur",
    label: "Individual/Entrepreneur",
    description:
      "Already started your entrepreneurial journey, either with an idea or a newly established business.",
    icon: "💡",
  },
  {
    id: "mentor",
    label: "Mentor",
    description:
      "A person who shares their knowledge and experience to guide and support others.",
    icon: "🎓",
  },
  {
    id: "service-partner",
    label: "Service Partner",
    description:
      "Freelancers, agencies, or companies offering professional services to startups and businesses.",
    icon: "🤝",
  },
  {
    id: "startup",
    label: "Startup",
    description:
      "A company in early stages of development and looking to scale.",
    icon: "🚀",
  },
  {
    id: "incubator",
    label: "Incubator",
    description:
      "An organization that provides startups with workspace, mentorship, and resources.",
    icon: "📊",
  },
  {
    id: "accelerator",
    label: "Accelerator",
    description:
      "A program that helps startups grow rapidly through mentorship, funding and connections.",
    icon: "⚡",
  },
  {
    id: "individual-investor",
    label: "Individual Investor",
    description: "An individual who invest their own money in companies.",
    icon: "🏦",
  },
  {
    id: "institutional-investor",
    label: "Institutional Investor",
    description:
      "An organization that invest money on behalf of others, such as pension funds or insurance companies.",
    icon: "🏛️",
  },
  {
    id: "trade-bodies",
    label: "Trade Bodies",
    description:
      "Organizations that represent the interests of businesses in a particular sector.",
    icon: "⚙️",
  },
  {
    id: "government-body",
    label: "Government body",
    description:
      "A department or agency of the government that supports startups.",
    icon: "🛡️",
  },
  {
    id: "corporate",
    label: "Corporate",
    description: "A large company that invests in or partners with startups.",
    icon: "📚",
  },
  {
    id: "technology-partner",
    label: "Technology partner",
    description: "A company that provides technology or services to startups.",
    icon: "💻",
  },
];

export const SKILLS_LIST = [
  "Accounting",
  "Aerospace Engineering",
  "Agro Tech",
  "AI Development",
  "Android Development",
  "Art",
  "Backend Development",
  "Blockchain",
  "Brand Building",
  "Business Analysis",
  "Business Strategy",
  "Cloud Architecture",
  "Content Strategy",
  "Customer Success",
  "Cybersecurity",
  "Data Science",
  "Digital Marketing",
  "E-commerce",
  "Finance",
  "Frontend Development",
  "Full Stack Development",
  "Growth Hacking",
  "HR / Talent",
  "iOS Development",
  "Legal",
  "Machine Learning",
  "Marketing",
  "Mobile Development",
  "Product Management",
  "Project Management",
  "Sales",
  "SEO/SEM",
  "Software Architecture",
  "Supply Chain",
  "UI/UX Design",
  "Web Development",
];

export const ROLE_LEVELS = [
  "Entry Level",
  "Intermediate",
  "Senior / Lead",
  "Manager",
  "Director / Head",
  "VP",
  "CXO",
  "Researcher",
  "Senior Researcher / Research Lead",
  "Principal Researcher",
];

export const TEAM_SIZES = [
  "1-10 employees",
  "11-50 employees",
  "51-200 employees",
  "201-500 employees",
  "500+ employees",
];

export const STARTUP_TEAM_SIZES = [
  "Solo Founder",
  "2-5",
  "6-10",
  "11-25",
  "26-50",
  "50+",
];

export const STARTUP_STAGES = [
  {
    id: "idea-concept",
    label: "Idea/Concept",
    description: "Just an idea, pre-MVP",
    icon: "💡",
  },
  {
    id: "mvp-development",
    label: "MVP Development",
    description: "Building the minimum viable product",
    icon: "🔨",
  },
  {
    id: "pre-launch",
    label: "Pre-Launch",
    description: "MVP ready, preparing to launch",
    icon: "🚀",
  },
  {
    id: "launched-beta",
    label: "Launched (Beta)",
    description: "Publicly launched in beta",
    icon: "🌱",
  },
  {
    id: "launched-public",
    label: "Launched (Public)",
    description: "Fully launched and operational",
    icon: "✨",
  },
  {
    id: "scaling-growth",
    label: "Scaling/Growth",
    description: "Growing and scaling operations",
    icon: "📈",
  },
  {
    id: "pivoting",
    label: "Pivoting",
    description: "Changing direction or business model",
    icon: "🔄",
  },
];

export const STARTUP_VISIBILITY_MODES = [
  {
    id: "public",
    label: "Public",
    description: "Visible to everyone",
    icon: "🌐",
  },
  {
    id: "stealth",
    label: "Stealth Mode",
    description: "Name hidden, show industry/tags only",
    icon: "🕵️",
  },
  {
    id: "idea-stage",
    label: "Idea Stage",
    description: "Special badge for pre-launch ideas",
    icon: "💭",
  },
];

export const STARTUP_SEEKING_OPTIONS = [
  "Mentorship",
  "Co-founders",
  "Investors/Funding",
  "Technical Talent",
  "Business Development Partners",
  "Marketing/PR Help",
  "Legal/Compliance Advice",
  "Product Feedback",
  "Beta Testers",
  "Strategic Partnerships",
];

export const STARTUP_FUNDING_STATUS = [
  "Bootstrapped",
  "Pre-Seed",
  "Seed",
  "Series A",
  "Series B+",
  "Not Seeking Funding",
];

export const TARGET_MARKETS = ["B2B", "B2C", "B2B2C", "Marketplace"];

export const COMPANY_STAGES = [
  {
    id: "early-stage",
    label: "Early Stage Startup",
    description: "Pre-seed, Seed, Bootstrapped (0-$1M funding)",
    icon: "🌱",
  },
  {
    id: "funded-startup",
    label: "Funded Startup",
    description: "Series A/B/C+ ($1M+ funding)",
    icon: "🚀",
  },
  {
    id: "revenue-stage",
    label: "Revenue Stage",
    description: "Generating revenue, profitable, scaling",
    icon: "📈",
  },
  {
    id: "established",
    label: "Established Company",
    description: "Mature, stable operations",
    icon: "🏢",
  },
  {
    id: "enterprise",
    label: "Enterprise",
    description: "Large corporation (1000+ employees)",
    icon: "🏛️",
  },
];

export const INDUSTRY_EXPERTISE = {
  "Technology / Software": [
    "Backend Development",
    "Frontend Development",
    "Full Stack",
    "AI/ML",
    "DevOps",
    "Cloud Architecture",
    "Cybersecurity",
    "Mobile Development",
  ],
  Engineering: [
    "Mechanical Engineering",
    "Electrical Engineering",
    "Civil Engineering",
    "Software Architecture",
    "Systems Design",
    "IoT",
    "Embedded Systems",
    "Automotive Engineering",
    "Electronics Engineering",
    "Robotics Engineering",
    "EV (Electric Vehicle) Technology",
    "Aerospace Engineering",
    "Chemical Engineering",
    "Biomedical Engineering",
    "Petroleum Engineering",
    "Environmental Engineering",
  ],
  Product: [
    "Product Strategy",
    "Product Roadmap",
    "User Research",
    "Product Launch",
    "Market Analysis",
    "Feature Prioritization",
    "Analytics",
    "Product Management",
  ],
  Finance: [
    "Financial Planning",
    "Investment Strategy",
    "Risk Management",
    "Portfolio Management",
    "Corporate Finance",
    "FP&A",
    "Treasury Management",
    "Mergers & Acquisitions",
  ],
  Marketing: [
    "Digital Marketing",
    "Content Strategy",
    "Brand Building",
    "Growth Hacking",
    "SEO/SEM",
    "Social Media Strategy",
    "Marketing Analytics",
    "Campaign Management",
  ],
  Legal: [
    "Contract Law",
    "Intellectual Property",
    "Corporate Law",
    "Compliance",
    "Litigation",
    "Regulatory Affairs",
    "Employment Law",
    "Privacy Law",
  ],
  "HR / Talent": [
    "Talent Acquisition",
    "Employee Development",
    "Compensation & Benefits",
    "Organizational Design",
    "Culture & Engagement",
    "Performance Management",
    "Learning & Development",
    "Labor Relations",
  ],
  Healthcare: [
    "Clinical Practice",
    "Healthcare Management",
    "Medical Research",
    "Health Policy",
    "Pharmaceuticals",
    "Medical Device",
    "Healthcare Technology",
    "Public Health",
  ],
  Manufacturing: [
    "Supply Chain",
    "Operations Management",
    "Quality Control",
    "Lean Manufacturing",
    "Automation",
    "Production Planning",
    "Maintenance Management",
    "Industrial Engineering",
  ],
  EdTech: [
    "Curriculum Design",
    "Learning Analytics",
    "Instructional Design",
    "EdTech Strategy",
    "Digital Learning",
    "Assessment Design",
    "Student Engagement",
    "EdTech Product",
  ],
  Consulting: [
    "Strategy Consulting",
    "Operations Consulting",
    "Digital Transformation",
    "Change Management",
    "Business Analysis",
    "Process Improvement",
    "Client Relations",
    "Project Management",
  ],
  SaaS: [
    "SaaS Product Strategy",
    "Customer Success",
    "Sales & Revenue",
    "SaaS Marketing",
    "Subscription Model",
    "Churn Reduction",
    "Pricing Strategy",
    "SaaS Operations",
  ],
  "E-commerce": [
    "E-commerce Strategy",
    "Conversion Optimization",
    "User Experience",
    "Inventory Management",
    "Logistics & Fulfillment",
    "Payment Processing",
    "Customer Retention",
    "Marketplace Management",
  ],
  "Mobility / Logistics": [
    "Supply Chain Optimization",
    "Fleet Management",
    "Route Optimization",
    "Warehouse Management",
    "Last-Mile Delivery",
    "Mobility Solutions",
    "Transportation",
    "Logistics Technology",
  ],
  "Real Estate": [
    "Real Estate Development",
    "Property Management",
    "Commercial Real Estate",
    "Residential Real Estate",
    "Real Estate Investment",
    "Valuation",
    "Real Estate Finance",
    "Urban Planning",
  ],
  "Web3 / AI": [
    "Blockchain Development",
    "Smart Contracts",
    "DeFi Strategy",
    "NFT Strategy",
    "AI Strategy",
    "Machine Learning",
    "Web3 Product",
    "Cryptocurrency",
  ],
};
